// Otomatik üretildi (assets-pipeline/coverage.ts). Elle düzenlemeyin.
/** Her vücut modelinde gerçekten bulunan yapılar ve bölüm adları (GLB düğümlerinden). */
export const MODEL_COVERAGE: Record<'male' | 'female', Record<string, string[]>> = {
 "male": {
  "skin": [],
  "bones": [
   "femur-l",
   "femur-r",
   "foot-l",
   "foot-r",
   "forearm-l",
   "forearm-r",
   "hand-l",
   "hand-r",
   "humerus-l",
   "humerus-r",
   "leg-l",
   "leg-r",
   "pelvis",
   "ribcage",
   "shoulder-l",
   "shoulder-r",
   "skull",
   "spine"
  ],
  "knee": [
   "acl",
   "cartilage",
   "collateral",
   "meniscus",
   "patellar",
   "pcl"
  ],
  "pituitary": [],
  "adrenals": [
   "left",
   "right"
  ],
  "stomach": [],
  "esophagus": [],
  "liver": [
   "capsule",
   "caudate",
   "left-lobe",
   "ligaments",
   "porta",
   "quadrate",
   "right-lobe"
  ],
  "gallbladder": [
   "bile-ducts",
   "gallbladder"
  ],
  "pancreas": [
   "body",
   "ducts",
   "head",
   "tail"
  ],
  "small-intestine": [
   "duodenum",
   "ileum",
   "jejunum"
  ],
  "large-intestine": [
   "ascending",
   "cecum",
   "descending",
   "rectum",
   "sigmoid",
   "transverse"
  ],
  "kidneys": [
   "capsule",
   "column",
   "cortex",
   "hilum",
   "papilla",
   "pyramid"
  ],
  "urinary-tract": [
   "bladder",
   "bladder-neck",
   "calyces",
   "renal-pelvis",
   "trigone",
   "ureter",
   "urethra"
  ],
  "prostate": [
   "apex-base",
   "central",
   "ducts",
   "peripheral",
   "stroma",
   "transition"
  ],
  "testes": [
   "left",
   "right"
  ],
  "male-genitals": [
   "penis",
   "seminal-vesicles",
   "vas-deferens"
  ],
  "diaphragm": [],
  "lungs": [
   "hilum",
   "left-lower",
   "left-upper",
   "right-lower",
   "right-middle",
   "right-upper"
  ],
  "airways": [
   "bronchial-cartilage",
   "epiglottis",
   "larynx",
   "lobar-bronchi",
   "main-bronchi",
   "segmental-bronchi",
   "trachea",
   "tracheal-rings"
  ],
  "nerves": [
   "brachial",
   "femoral",
   "median",
   "peroneal",
   "radial",
   "sciatic",
   "tibial",
   "ulnar",
   "vagus"
  ],
  "brain": [
   "amygdala",
   "auditory",
   "basal-nuclei",
   "cerebellum",
   "cingulate",
   "corpus-callosum",
   "frontal",
   "hippocampus",
   "insula",
   "medulla",
   "midbrain",
   "motor",
   "occipital",
   "olfactory",
   "parietal",
   "pons",
   "sensory",
   "temporal",
   "thalamus",
   "ventricles",
   "visual-pathway",
   "white-matter"
  ],
  "pineal": [],
  "hypothalamus": [
   "regions"
  ],
  "spinal-cord": [
   "cervical",
   "lumbar",
   "sacral",
   "thoracic"
  ],
  "eyes": [
   "aqueous",
   "choroid",
   "ciliary",
   "conjunctiva",
   "cornea",
   "iris",
   "lens",
   "macula",
   "muscles",
   "optic-disc",
   "optic-nerve",
   "retina",
   "sclera",
   "vitreous",
   "zonule"
  ],
  "spleen": [
   "hilum",
   "surface"
  ],
  "thymus": [],
  "tonsils": [],
  "lymph-node": [
   "afferent",
   "capsule",
   "efferent",
   "follicles",
   "medulla",
   "paracortex",
   "vessels"
  ],
  "carotid-arteries": [
   "brachiocephalic artery a",
   "brachiocephalic artery b",
   "left common carotid artery a",
   "left common carotid artery b",
   "left subclavian artery",
   "left subclavian artery a",
   "left subclavian artery b",
   "right common carotid artery",
   "right subclavian artery"
  ],
  "abdominal-vessels": [
   "anterior segmental right hepatic artery",
   "celiac trunk",
   "common hepatic artery",
   "cystic artery",
   "cystic vein",
   "hepatic portal vein",
   "ileocolic artery",
   "ileocolic vein",
   "inferior mesenteric artery",
   "inferior mesenteric vein",
   "inferior pancreaticoduodenal vein",
   "inferior rectal vein L",
   "inferior rectal vein R",
   "internal pudendal vein L",
   "internal pudendal vein R",
   "left branch of portal vein",
   "left colic artery",
   "left colic vein",
   "left common iliac artery",
   "left external iliac artery",
   "left hepatic artery",
   "left hepatic vein",
   "left internal iliac artery",
   "marginal artery of Drummond",
   "median sacral vein",
   "middle colic artery",
   "middle colic vein",
   "middle hepatic artery branch of left hepatic artery",
   "middle hepatic vein",
   "middle rectal vein L",
   "middle rectal vein R",
   "portal vein",
   "posterior segmental right hepatic artery",
   "proper hepatic artery",
   "right branch of portal vein",
   "right colic artery",
   "right colic vein",
   "right common iliac artery",
   "right external iliac artery",
   "right hepatic artery",
   "right hepatic vein",
   "right internal iliac artery",
   "sigmoid artery a",
   "sigmoid artery b",
   "sigmoid artery c",
   "sigmoid vein",
   "splenic artery",
   "splenic vein",
   "superior mesenteric artery",
   "superior mesenteric vein",
   "superior rectal vein"
  ],
  "veins": [
   "anterior cardiac vein",
   "brachiocephalic vein L",
   "brachiocephalic vein R",
   "common iliac vein L",
   "common iliac vein R",
   "coronary sinus",
   "external iliac vein L",
   "external iliac vein R",
   "great cardiac vein",
   "inferior vena cava a",
   "inferior vena cava b",
   "internal iliac vein L",
   "internal iliac vein R",
   "left internal jugular vein",
   "left subclavian vein",
   "middle cardiac vein",
   "oblique vein of left atrium",
   "posterior vein of left ventricle",
   "right internal jugular vein",
   "right subclavian vein",
   "small cardiac vein",
   "superior vena cava"
  ],
  "limb-vessels": [
   "left anterior tibial artery",
   "left axillary and brachial artery",
   "left axillary and brachial vein",
   "left basilic vein",
   "left cephalic vein",
   "left femoral and popliteal artery",
   "left femoral and popliteal vein",
   "left great saphenous vein",
   "left palmar arch",
   "left posterior tibial artery",
   "left radial artery",
   "left small saphenous vein",
   "left ulnar artery",
   "right anterior tibial artery",
   "right axillary and brachial artery",
   "right axillary and brachial vein",
   "right basilic vein",
   "right cephalic vein",
   "right femoral and popliteal artery",
   "right femoral and popliteal vein",
   "right great saphenous vein",
   "right palmar arch",
   "right posterior tibial artery",
   "right radial artery",
   "right small saphenous vein",
   "right ulnar artery"
  ],
  "heart": [
   "aortic-valve",
   "left-atrium",
   "left-ventricle",
   "mitral",
   "papillary",
   "pulmonary-valve",
   "right-atrium",
   "right-ventricle",
   "septum",
   "tricuspid"
  ],
  "eye-vessels": [
   "central retinal artery L",
   "central retinal artery R",
   "central retinal vein L",
   "central retinal vein R",
   "inferior ophthalmic vein L",
   "inferior ophthalmic vein R",
   "long posterior ciliary artery L",
   "long posterior ciliary artery R",
   "ophthalmic vein L",
   "ophthalmic vein R",
   "opthalmic artery L",
   "opthalmic artery R",
   "superior ophthalmic vein L",
   "superior ophthalmic vein R"
  ],
  "renal-vessels": [
   "left renal artery",
   "renal vein L",
   "renal vein R",
   "right renal artery"
  ],
  "aorta": [
   "aortic arch",
   "ascending aorta",
   "descending aorta a",
   "descending aorta b"
  ],
  "coronary-arteries": [
   "diagonal branch of anterior descending branch of left coronary artery",
   "diagonal branch of left anterior descending artery",
   "left anterior descending artery",
   "left coronary artery",
   "left marginal branch",
   "right coronary artery",
   "right marginal artery",
   "right posterior descending artery"
  ],
  "pulmonary-vessels": [
   "pulmonary artery L",
   "pulmonary artery R",
   "pulmonary trunk",
   "pulmonary vein L inf",
   "pulmonary vein L sup",
   "pulmonary vein R inf",
   "pulmonary vein R sup"
  ],
  "skeletal-muscle": [
   "abdomen",
   "back",
   "forearm-l",
   "forearm-r",
   "head",
   "hip-l",
   "hip-r",
   "leg-l",
   "leg-r",
   "neck",
   "thigh-l",
   "thigh-r",
   "thorax",
   "upper-arm-l",
   "upper-arm-r"
  ]
 },
 "female": {
  "skin": [],
  "bones": [
   "femur-l",
   "femur-r",
   "foot-l",
   "foot-r",
   "forearm-l",
   "forearm-r",
   "hand-l",
   "hand-r",
   "humerus-l",
   "humerus-r",
   "leg-l",
   "leg-r",
   "pelvis",
   "ribcage",
   "shoulder-l",
   "shoulder-r",
   "skull",
   "spine"
  ],
  "knee": [
   "acl",
   "cartilage",
   "collateral",
   "meniscus",
   "patellar",
   "pcl"
  ],
  "pituitary": [],
  "adrenals": [
   "left",
   "right"
  ],
  "stomach": [],
  "esophagus": [],
  "liver": [
   "capsule",
   "caudate",
   "left-lobe",
   "ligaments",
   "porta",
   "quadrate",
   "right-lobe"
  ],
  "gallbladder": [
   "bile-ducts",
   "gallbladder"
  ],
  "pancreas": [
   "body",
   "ducts",
   "head",
   "tail"
  ],
  "small-intestine": [
   "duodenum",
   "ileum",
   "jejunum"
  ],
  "large-intestine": [
   "ascending",
   "cecum",
   "descending",
   "rectum",
   "sigmoid",
   "transverse"
  ],
  "kidneys": [
   "capsule",
   "column",
   "cortex",
   "hilum",
   "papilla",
   "pyramid"
  ],
  "urinary-tract": [
   "bladder",
   "bladder-neck",
   "calyces",
   "renal-pelvis",
   "trigone",
   "ureter"
  ],
  "fallopian-tubes": [
   "ampulla",
   "infundibulum",
   "isthmus"
  ],
  "uterus": [
   "body",
   "cervix",
   "fundus",
   "ligaments",
   "lower-segment"
  ],
  "ovaries": [
   "left",
   "right"
  ],
  "vagina": [
   "vagina"
  ],
  "breasts": [
   "ducts",
   "fat",
   "ligaments",
   "lobes",
   "nipple"
  ],
  "diaphragm": [],
  "lungs": [
   "hilum",
   "left-lower",
   "left-upper",
   "right-lower",
   "right-middle",
   "right-upper"
  ],
  "airways": [
   "epiglottis",
   "larynx",
   "lobar-bronchi",
   "segmental-bronchi",
   "trachea",
   "tracheal-rings"
  ],
  "nerves": [
   "brachial",
   "femoral",
   "median",
   "peroneal",
   "radial",
   "sciatic",
   "tibial",
   "ulnar",
   "vagus"
  ],
  "brain": [
   "amygdala",
   "auditory",
   "basal-nuclei",
   "cerebellum",
   "cingulate",
   "corpus-callosum",
   "frontal",
   "hippocampus",
   "insula",
   "medulla",
   "midbrain",
   "motor",
   "occipital",
   "olfactory",
   "parietal",
   "pons",
   "sensory",
   "temporal",
   "thalamus",
   "ventricles",
   "visual-pathway",
   "white-matter"
  ],
  "pineal": [],
  "hypothalamus": [
   "regions"
  ],
  "spinal-cord": [
   "cervical",
   "lumbar",
   "sacral",
   "thoracic"
  ],
  "eyes": [
   "aqueous",
   "choroid",
   "ciliary",
   "conjunctiva",
   "cornea",
   "iris",
   "lens",
   "macula",
   "muscles",
   "optic-disc",
   "optic-nerve",
   "retina",
   "sclera",
   "vitreous",
   "zonule"
  ],
  "spleen": [
   "hilum",
   "surface"
  ],
  "thymus": [],
  "tonsils": [],
  "lymph-node": [
   "afferent",
   "capsule",
   "efferent",
   "follicles",
   "medulla",
   "paracortex",
   "vessels"
  ],
  "carotid-arteries": [
   "brachiocephalic artery a",
   "brachiocephalic artery b",
   "left common carotid artery a",
   "left common carotid artery b",
   "left subclavian artery",
   "left subclavian artery a",
   "left subclavian artery b",
   "right common carotid artery",
   "right subclavian artery"
  ],
  "abdominal-vessels": [
   "anterior segmental right hepatic artery",
   "celiac trunk",
   "common hepatic artery",
   "cystic artery",
   "cystic vein",
   "hepatic portal vein",
   "ileocolic artery",
   "ileocolic vein",
   "inferior mesenteric artery",
   "inferior mesenteric vein",
   "inferior pancreaticoduodenal vein",
   "inferior rectal vein L",
   "inferior rectal vein R",
   "internal pudendal vein L",
   "internal pudendal vein R",
   "left branch of portal vein",
   "left circumflex artery",
   "left colic artery",
   "left colic vein",
   "left common iliac artery",
   "left external iliac artery",
   "left hepatic artery",
   "left hepatic vein",
   "left internal iliac artery",
   "left marginal vein",
   "left uterine artery",
   "left uterine vein",
   "marginal artery of Drummond",
   "median sacral vein",
   "middle colic artery",
   "middle colic vein",
   "middle hepatic artery branch of left hepatic artery",
   "middle hepatic vein",
   "middle rectal vein L",
   "middle rectal vein R",
   "posterior left ventricular branch",
   "posterior segmental right hepatic artery",
   "proper hepatic artery",
   "right branch of portal vein",
   "right colic artery",
   "right colic vein",
   "right common iliac artery",
   "right external iliac artery",
   "right hepatic artery",
   "right hepatic vein",
   "right internal iliac artery",
   "right uterine artery",
   "right uterine vein",
   "sigmoid artery a",
   "sigmoid artery b",
   "sigmoid artery c",
   "sigmoid vein a",
   "sigmoid vein b",
   "sigmoid vein c",
   "splenic artery",
   "splenic vein",
   "superior mesenteric artery",
   "superior mesenteric vein",
   "superior rectal artery",
   "superior rectal vein"
  ],
  "veins": [
   "anterior cardiac vein",
   "coronary sinus",
   "great cardiac vein",
   "inferior vena cava a",
   "inferior vena cava b",
   "internal iliac vein L",
   "internal iliac vein R",
   "left common iliac vein",
   "left internal jugular vein",
   "left subclavian vein",
   "middle cardiac vein",
   "oblique vein of left atrium",
   "posterior vein of left ventricle",
   "right common iliac vein",
   "right internal jugular vein",
   "right subclavian vein",
   "small cardiac vein",
   "superior vena cava"
  ],
  "limb-vessels": [
   "left anterior tibial artery",
   "left axillary and brachial artery",
   "left axillary and brachial vein",
   "left basilic vein",
   "left cephalic vein",
   "left femoral and popliteal artery",
   "left femoral and popliteal vein",
   "left great saphenous vein",
   "left palmar arch",
   "left posterior tibial artery",
   "left radial artery",
   "left small saphenous vein",
   "left ulnar artery",
   "right anterior tibial artery",
   "right axillary and brachial artery",
   "right axillary and brachial vein",
   "right basilic vein",
   "right cephalic vein",
   "right femoral and popliteal artery",
   "right femoral and popliteal vein",
   "right great saphenous vein",
   "right palmar arch",
   "right posterior tibial artery",
   "right radial artery",
   "right small saphenous vein",
   "right ulnar artery"
  ],
  "heart": [
   "aortic-valve",
   "left-atrium",
   "left-ventricle",
   "mitral",
   "papillary",
   "pulmonary-valve",
   "right-atrium",
   "right-ventricle",
   "septum",
   "tricuspid"
  ],
  "eye-vessels": [
   "central retinal artery L",
   "central retinal artery R",
   "central retinal vein L",
   "central retinal vein R",
   "inferior ophthalmic vein L",
   "inferior ophthalmic vein R",
   "long posterior ciliary artery L",
   "long posterior ciliary artery R",
   "ophthalmic vein L",
   "ophthalmic vein R",
   "opthalmic artery L",
   "opthalmic artery R",
   "superior ophthalmic vein L",
   "superior ophthalmic vein R"
  ],
  "renal-vessels": [
   "left renal artery",
   "left renal vein",
   "right renal artery",
   "right renal vein"
  ],
  "pulmonary-vessels": [
   "pulmonary artery L",
   "pulmonary artery R",
   "pulmonary trunk",
   "pulmonary vein L inf",
   "pulmonary vein L sup",
   "pulmonary vein R inf",
   "pulmonary vein R sup"
  ],
  "coronary-arteries": [
   "diagonal branch of left anterior descending artery",
   "left anterior descending artery",
   "left coronary artery",
   "left marginal branch",
   "left posterior descending branch of circumflex branch of left coronary artery",
   "right coronary artery",
   "right marginal artery"
  ],
  "aorta": [
   "aortic arch",
   "ascending aorta",
   "descending aorta a",
   "descending aorta b"
  ],
  "skeletal-muscle": [
   "abdomen",
   "back",
   "forearm-l",
   "forearm-r",
   "head",
   "hip-l",
   "hip-r",
   "leg-l",
   "leg-r",
   "neck",
   "thigh-l",
   "thigh-r",
   "thorax",
   "upper-arm-l",
   "upper-arm-r"
  ]
 }
};
